# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CFPicGame' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking' 
pod 'YYKit', '~> 1.0.9' 
pod 'Masonry'
pod 'SDWebImage' 

  # Pods for CFPicGame

  target 'CFPicGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CFPicGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
